spring:
  config:
    import: optional:classpath:.docker-env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

server:
  port: ${SPRING_PORT}