spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: rating-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ChangeAvgDoctorRatingEvent:com.tserashkevich.ratingservice.dtos.kafka.ChangeAvgDoctorRatingEvent
      change-avg-doctor-rating-topic:
        name: change-avg-doctor-rating-topic
      retries: 3
  cloud:
    openfeign:
      client:
        config:
          appointment:
            url: http://localhost:8082/api/v1/appointments
            connect-timeout: 3000
            read-timeout: 5000

resilience4j:
  retry:
    instances:
      retry-conf:
        max-attempts: 3
        wait-duration: 1s
        ignore-exceptions:
          - com.tserashkevich.ratingservice.exceptions.feign.OtherServiceNotFoundException
  circuitbreaker:
    instances:
      circuitbreaker-conf:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 20s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        ignore-exceptions:
          - com.tserashkevich.ratingservice.exceptions.feign.OtherServiceNotFoundException

eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: ${SPRING_PORT}