spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: rating-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ChangeAvgDoctorRatingEvent:com.tserashkevich.ratingservice.dtos.kafka.ChangeAvgDoctorRatingEvent
      change-avg-doctor-rating-topic:
        name: change-avg-doctor-rating-topic
      retries: 3

eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: ${SPRING_PORT}