spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/v1/patients/**
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/doctors/**
        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/api/v1/appointments/**,/api/v1/work-days/**
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/v1/services/**
        - id: medical-history-service
          uri: lb://MEDICAL-HISTORY-SERVICE
          predicates:
            - Path=/api/v1/records/**
        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/api/v1/feedbacks/**
        - id: eureka-server
          uri: http://eureka@localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: ${SPRING_PORT}