spring:
  config:
    import: optional:classpath:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/v1/patients/**
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/v1/doctors/**
        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/api/v1/appointments/**
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/v1/services/**
        - id: eureka-server
          uri: http://eureka@discovery-service:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka@discovery-service:8761/eureka/

server:
  port: ${SPRING_PORT}