spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: medical-history-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    openfeign:
      client:
        config:
          appointment:
            url: http://localhost:8082/api/v1/appointments
            connect-timeout: 3000
            read-timeout: 5000

resilience4j:
  retry:
    instances:
      retry-conf:
        max-attempts: 3
        wait-duration: 1s
        ignore-exceptions:
          - com.tserashkevich.medicalhistoryservice.exceptions.AppointmentNotFoundException
  circuitbreaker:
    instances:
      circuitbreaker-conf:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 20s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        ignore-exceptions:
          - com.tserashkevich.medicalhistoryservice.exceptions.AppointmentNotFoundException

eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mongock:
  migration-scan-package:
    - com.tserashkevich.medicalhistoryservice.migrations

minio:
  bucket: ${MINIO_BUCKET}
  host: ${MINIO_HOST}
  port: ${MINIO_PORT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

server:
  port: ${SPRING_PORT}