package com.tserashkevich.appointmentservice.utils;

import lombok.experimental.UtilityClass;

@UtilityClass
public class LogList {
    public final String NOT_FOUND_ERROR = "Not found exception thrown: {}";
    public final String BAD_REQUEST_ERROR = "Bed request exception: {}";
    public final String METHOD_ARGUMENT_ERROR = "Not valid method argument exception thrown: {}";
    public final String CONSTRAINT_VIOLATION_ERROR = "Failed parameter verification exception thrown: {}";
    public final String BAD_REQUEST_OTHER_SERVICE = "Bad request, other service: {}";
    public final String NOT_FOUND_OTHER_SERVICE = "Not found, other service: {}";
    public final String SERVER_OTHER_SERVICE = "Server, other service: {}";
    public final String CREATE_APPOINTMENT = "Appointment created with ID: {}";
    public final String DELETE_APPOINTMENT = "Appointment deleted with ID: {}";
    public final String GENERATE_APPOINTMENTS = "Appointments generated by work day with ID: {}";
    public final String REGENERATE_APPOINTMENTS = "Appointments regenerated by work day with ID: {}";
    public final String DELETE_APPOINTMENTS = "Appointments deleted by work day with ID: {}";
    public final String FIND_ALL_APPOINTMENTS = "Found all appointments";
    public final String FIND_APPOINTMENT = "Found appointments with ID: {}";
    public final String SEARCH_APPOINTMENT = "Search appointment with searchline: {}";
    public final String FREE_APPOINTMENT = "Free appointment with id {}";
    public final String BOOK_APPOINTMENT = "Book appointment with id {} by patient {}";
    public final String CHECK_IN_APPOINTMENT = "Check in appointment with id {}";
    public final String IN_PROGRESS_APPOINTMENT = "In progress appointment with id {}";
    public final String COMPLETE_APPOINTMENT = "Complete appointment with id {}";
    public final String NO_SHOW_APPOINTMENT = "No-show appointment with id {}";
    public final String CREATE_DOCTOR_WORK_DAY = "Doctor work day created with ID: {}";
    public final String DELETE_DOCTOR_WORK_DAY = "Doctor work day deleted with ID: {}";
    public final String FIND_ALL_DOCTOR_WORK_DAYS = "Found all doctor work days";
    public final String FIND_DOCTOR_WORK_DAY = "Found doctor work days with ID: {}";
    public final String SEARCH_DOCTOR_WORK_DAY = "Search doctor work day with searchline: {}";
    public final String RECEIVED_DOCTOR = "Received doctor with ID: {}";
    public final String RECEIVED_PATIENT = "Received patient with ID: {}";
    public final String RECEIVED_SERVICES = "Received services with ID: {}";

}