spring:
  config:
    import: optional:classpath:.docker-env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka@discovery-service:8761/eureka/

minio:
  bucket: ${MINIO_BUCKET}
  host: ${MINIO_HOST}
  port: ${MINIO_PORT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

server:
  port: ${SPRING_PORT}