spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: patient-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

minio:
  bucket: ${MINIO_BUCKET}
  host: ${MINIO_HOST}
  port: ${MINIO_PORT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

server:
  port: ${SPRING_PORT}