spring:
  config:
    import: optional:classpath:.docker-env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    openfeign:
      client:
        config:
          appointment:
            url: http://appointment-service:8082/api/v1/appointments
            connect-timeout: 3000
            read-timeout: 5000

server:
  port: ${SPRING_PORT}